import React, { useEffect, useState } from "react";
import { api } from "../api/client.js";
import RemedyCard from "../components/RemedyCard.jsx";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";

function assetUrl(maybeUrl) {
  if (!maybeUrl) return null;
  // Backend returns absolute paths like "/assets/xyz.png".
  if (maybeUrl.startsWith("/")) return `${API_BASE_URL}${maybeUrl}`;
  return maybeUrl;
}

function MetricItem({ label, value }) {
  return (
    <div style={{ padding: "10px 12px", border: "1px solid var(--border)", borderRadius: 12 }}>
      <div className="muted" style={{ fontSize: 13, marginBottom: 6 }}>
        {label}
      </div>
      <div style={{ fontWeight: 900 }}>{value}</div>
    </div>
  );
}

export default function Dashboard() {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    let mounted = true;
    async function load() {
      try {
        setLoading(true);
        const res = await api.get("/api/artifacts");
        if (!mounted) return;
        setData(res.data);
        setError(null);
      } catch (e) {
        if (!mounted) return;
        setError(e?.response?.data?.detail || e.message || "Failed to load artifacts");
      } finally {
        if (mounted) setLoading(false);
      }
    }
    load();
    return () => {
      mounted = false;
    };
  }, []);

  if (loading) {
    return (
      <div className="panel">
        <div className="panelTitle">Loading dashboard...</div>
        <div className="muted">Fetching model card + saved plots</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="panel">
        <div className="panelTitle">Error</div>
        <div className="error">{String(error)}</div>
      </div>
    );
  }

  const modelCard = data?.model_card;
  const artifacts = data?.artifacts || {};
  const explanationImages = artifacts.explanations || [];

  const verification = modelCard?.verification || {};

  return (
    <>
      <div className="panel">
        <h2 className="panelTitle">{modelCard?.model_name || "DoshaNet"}</h2>
        <div className="muted">Model overview, metrics, and saved explainability outputs.</div>
      </div>

      <div className="grid2">
        <div className="panel">
          <h3 className="panelTitle">Verification Metrics</h3>
          <div className="grid2">
            <MetricItem label="Test Accuracy" value={verification.test_accuracy ? `${verification.test_accuracy}%` : "—"} />
            <MetricItem label="Macro ROC-AUC" value={verification.macro_roc_auc ? `${verification.macro_roc_auc}` : "—"} />
            <MetricItem label="Cohen's Kappa" value={verification.cohens_kappa ? `${verification.cohens_kappa}` : "—"} />
            <MetricItem label="Wilcoxon p" value={verification.wilcoxon_p ? `${verification.wilcoxon_p}` : "—"} />
          </div>
        </div>

        <div className="panel">
          <h3 className="panelTitle">Confusion Matrix</h3>
          {artifacts.confusion_matrix_url ? (
            <div className="imgCard">
              <img src={assetUrl(artifacts.confusion_matrix_url)} alt="Confusion matrix" />
            </div>
          ) : (
            <div className="muted">No confusion matrix found.</div>
          )}
        </div>
      </div>

      <div className="panel">
        <h3 className="panelTitle">Saved Patient Explanations</h3>
        <div className="muted" style={{ marginBottom: 12 }}>
          Click-through gallery for explanation images (pre-generated by training).
        </div>

        {explanationImages.length === 0 ? (
          <div className="muted">No saved explanation images were found.</div>
        ) : (
          <div className="imgGrid">
            {explanationImages.map((img) => (
              <div key={img.patientIndex} className="imgCard" title={`Patient ${img.patientIndex}`}>
                <img src={assetUrl(img.url)} alt={`Explanation for patient ${img.patientIndex}`} />
              </div>
            ))}
          </div>
        )}
      </div>

      {/* This component is just a placeholder so the UI always shows how remedies look. */}
      <div className="panel">
        <h3 className="panelTitle">Remedy Preview</h3>
        <div className="muted" style={{ marginBottom: 12 }}>
          Remedies are returned after prediction. Here’s a sample.
        </div>
        <RemedyCard />
      </div>
    </>
  );
}

